### ISSUE TITLE
Re design the review section like this.

### ISSUE THREAD

**Issue by rahulsd380** [neon-lab-dev/interiordesign#48]
![image](https://github.com/user-attachments/assets/1fa90aeb-6465-486a-8005-b7e9c736ede9)
![image](https://github.com/user-attachments/assets/cb08128d-26ed-46ef-8fa9-8c95e81e20e2)

**Comment by adhikareeprayush** [comment]
![image](https://github.com/user-attachments/assets/f11c5016-0e55-4810-964f-b3896ea87c67)
I have implemented the modal like this and the review section like this 
![image](https://github.com/user-attachments/assets/7975bdff-9916-44c0-8721-57959d22dbe0)
Please check the pr
